spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: da6e4d8ab66cf332f372
            clientSecret: 2338a6b14f5325323542667d1a94fb3fe6e4b8df
          google:
            client-id: 412750279152-evb6hitc6r0tbclbm06m5iav0ci0dhn1.apps.googleusercontent.com
            client-secret: IZv4qhV5V9RvdO2c3Tbm_aSA